language: ruby

dist: trusty

sudo: false

before_install:
  - gem install bundler

install: echo "Skip default install."

script:
  - ./test/run.rb

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.4
  - 2.4.1
  - ruby-head
  - jruby

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
  fast_finish: true
