name: CI

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        ruby_version:
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - ruby-head
          - jruby
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
